version: '3.9'

services:
  ui:
    build: ./ui
    container_name: react-ui
    restart: always
    ports:
      - "3000:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build: ./api
    container_name: auth-api
    restart: always
    ports:
      - "5062:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql-db
    restart: always
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
